version: '3.8'

services:
  website:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: health-insurance
    environment:
      NODE_ENV: production
      PORT_LOCAL: 443
      MODE: local
      DB_PASSWORD: StrongPassword123*
      DB_NAME: health-insurance-db
      DB_USERNAME: db_user
      DB_PORT: 1433
      # COGNITO_USER_POOL_ID: eu-west-1_IKRz0uOSt
      LOCAL_URL: https://localhost:443
      # COGNITO_CLIENT_ID: 5a78s0qjfu23hdmibeqrhfaldf
      DB_ENDPOINT: sqlserver
      AWS_REGION: eu-west-1
    ports:
      - 80:80
      - 443:443

  sqlserver:
    build:
      context: ./
      dockerfile: ./Dockerfiledb
    container_name: health-insurance-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword123#
      - MSSQL_PID=Developer
    ports:
      - 1433:1433

  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ./local-db:/docker-entrypoint-initdb.d
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      bash -c ' /opt/mssql-tools/bin/sqlcmd -S sqlserver,1433 -U sa -P StrongPassword123# -d master -i docker-entrypoint-initdb.d/init.sql; echo "All done!"; '
